# docker-compose.yml
version: "3.9"
services:
  db:
    image: postgres:15
    environment: { POSTGRES_PASSWORD: paw, POSTGRES_DB: paw }
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  s3:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: paw
      MINIO_ROOT_PASSWORD: pawpawpaw
    ports: ["9000:9000","9001:9001"]
    volumes: ["./.data/minio:/data"]
  api:
    build: ./server
    environment:
      DATABASE_URL: postgres://postgres:paw@db:5432/paw
      REDIS_URL: redis://redis:6379
      S3_ENDPOINT: http://s3:9000
      S3_ACCESS_KEY: paw
      S3_SECRET_KEY: pawpawpaw
      S3_BUCKET: reels
      RENDER_QUEUE: render
    depends_on: [db,redis,s3]
    ports: ["3001:3001"]
  render:
    build: ./services/render
    environment:
      REDIS_URL: redis://redis:6379
      S3_ENDPOINT: http://s3:9000
      S3_ACCESS_KEY: paw
      S3_SECRET_KEY: pawpawpaw
      S3_BUCKET: reels
      RENDER_QUEUE: render
      API_URL: http://api:3001
    depends_on: [redis,s3,api]
