apiVersion: apps/v1
kind: Deployment
metadata:
  name: pawfectmatch-server
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pawfectmatch-server
  template:
    metadata:
      labels:
        app: pawfectmatch-server
    spec:
      containers:
      - name: server
        image: pawfectmatch/server:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: pawfectmatch-secrets
              key: mongodb-uri
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: pawfectmatch-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: pawfectmatch-secrets
              key: jwt-secret
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: pawfectmatch-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: pawfectmatch-secrets
              key: aws-secret-access-key
        - name: S3_BUCKET
          value: "pawfectmatch-media"
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: pawfectmatch-secrets
              key: stripe-secret-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pawfectmatch-server
  namespace: production
spec:
  selector:
    app: pawfectmatch-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

