name: Mobile CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/mobile/**'
      - 'packages/**'
      - '.github/workflows/mobile-ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/mobile/**'
      - 'packages/**'
      - '.github/workflows/mobile-ci.yml'

jobs:
  mobile-ci:
    name: Mobile CI Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Expo Doctor
        working-directory: apps/mobile
        run: pnpm exec expo-doctor

      - name: Run TypeScript typecheck
        working-directory: apps/mobile
        run: pnpm typecheck:mobile || pnpm exec tsc --noEmit

      - name: Run ESLint
        working-directory: apps/mobile
        run: pnpm lint || pnpm exec eslint . --ext .ts,.tsx

      - name: Run Jest tests
        working-directory: apps/mobile
        run: pnpm test:ci || pnpm exec jest --ci --coverage --maxWorkers=2

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: apps/mobile/coverage
          retention-days: 7

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let comment = '## Mobile CI Results ✅\n\n';
            comment += '- ✅ Expo Doctor: Passed\n';
            comment += '- ✅ TypeScript: Passed\n';
            comment += '- ✅ ESLint: Passed\n';
            comment += '- ✅ Tests: Passed\n';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
