name: UI Artifacts (Capture & Metrics)

on:
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: {}

concurrency:
  group: ui-artifacts-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android-capture:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Android debug APK
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon

      - name: Start Android emulator and run capture/metrics
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          target: google_apis
          profile: pixel_6
          script: |
            adb install -r android/app/build/outputs/apk/debug/app-debug.apk || true
            node scripts/ui-map.mjs
            # Home capture
            node scripts/ui-capture.mjs --screen Home --out home --duration 6 || true
            node scripts/ui-metrics.mjs --out home --duration 6 --deeplink 'pawfectmatch://home' || true
            # Matches capture
            node scripts/ui-capture.mjs --screen Matches --out matches --duration 6 || true
            node scripts/ui-metrics.mjs --out matches --duration 6 --deeplink 'pawfectmatch://matches' || true

      - name: Upload UI media
        uses: actions/upload-artifact@v4
        with:
          name: ui-media
          path: |
            docs/ui_media/**/*.png
            docs/ui_media/**/*.gif
            docs/ui_media/**/*.mp4
          if-no-files-found: ignore

      - name: Upload UI metrics
        uses: actions/upload-artifact@v4
        with:
          name: ui-metrics
          path: docs/ui_media/metrics/**/*.json
          if-no-files-found: ignore


